### ISSUE TITLE
Addressing a few issues

### ISSUE THREAD

**Issue by CoderMaximus** [Rearth/Oritech#140] opened 2024-11-02 11:47 UTC
### Issue description

Well to start off... I simply LOVE Oritech, but it does have its downsides, one of them, some instructions are actually hard to conceive, and also there are many items that either don't have a crafting recipe or they aren't in the manual, for example the carbon fiber strand, or the flux gate, or the enderic lens. how do you create those? There isn't a recipe and there isn't a way to create them depending on the manual. Thx anyways.

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

Latest

### Fabric API version

latest

### Oritech version

latest

**Comment by OakPlatinum** [comment] 2024-11-02 13:10
The guide book is still work in progress, and it will be better to understand later.
As for the crafting issue, did you install EMI or REI as well? Recipes for things like the flux gate are available on those recipe viewers.

_For @Rearth : ambiguous title, suggestion: **Guidebook Improvement And Unable To Find Recipes**, also **Duplicate of #121** , not so similar though_

**Comment by Rearth** [comment] 2024-11-02 14:13
Yeah we really need an ingame warning for people not using REI/EMI. I have no idea how the Tech Reborn devs manage their sanity. They got like 30M downloads with just REI support IIRC. The guide book still needs some improvements and is getting them slowly, but for recipes just use REI/EMI, as states in the mod description

**Closed as completed by Rearth** 2024-11-02 14:13 UTC

**Comment by CoderMaximus** [comment] 2024-11-03 03:23
I use JEI, i thought they were the same really...😅
