### ISSUE TITLE
Machines not reacting to add-ons being placed.

### ISSUE THREAD

**Issue by jshipley** [Rearth/Oritech#58] opened 2024-08-05 23:24 UTC
### Issue description

When I attach an add-on to a machine, there's no indication that it is actually being used by the machine.

For example, if I attach a capacitor to a Lava Generator it still has 100kE energy storage and will not run when that storage is filled. It is only after I right-click on the machine again that it registers the add-on and starts to charge the additional 2ME.

Machines should react to neighbor updates and initialize their connected add-ons.

### Steps to reproduce

1. Place Lava Generator and fill it with lava
2. Wait until Lava Generator is full of energy
3. Place Capacitor add-on on Lava Generator
4. Nothing happens.
5. Right-click on Lava Generator
6. See that Lava Generator is now using the add-on.

### Minecraft version

1.21 (Latest)

### Fabric loader version

0.16.0

### Fabric API version

0.100.8+1.21

### Oritech version

0.8.1

**Comment by pourgb** [comment] 2024-08-06 03:26
The code responsible for checking addons (initAddons) is called on a right click, so it's not running all the time? Check MachineAddonController.java line 41(correct if I'm wrong)
Edit: Also check FrameInteractionBlock.java, the onUse check if you right click on the block, then it checks if the frame is valid(is the machine core there) then calls initAddons, so it is explicitly called on a right click

**Comment by Rearth** [comment] 2024-08-06 16:52
That is working as intended. Addon blocks do have a visual indication of their current connection status. They have either pink or blue section, depending on their connection state. This is also mentioned in the guide book. This is to both keep the logic simple but also performant. Re-opening the machine after addons have been added is an acceptable solution for me. The issue is that addons arent always connected to the machines themselfes, but can also be connected to machine extenders. Yes we could listen to neighbor updates on machine extenders, but then that brings a whole lot of additional logic with it, along with some more questions/problems. 

For example, if an machine extender is built so it could connect to 2 machines. If we automatically initialize the addons without manually opening the UI, this would result in non-deterministic behaviour on which machine it connects to. Doing it via the UI is much clearer. It just connects all extends and addons that aren't yet connected.

Another edge case would be sections of machine extenders that arent connected to a machine yet, and then suddenly being connected. We'd have to recursivly add all the connected extenders and then all adjacent addons, with the potetial issue from above also being preset again.

I know these could all theretically be solved somehow, but that would add a whole lot of additional complexity for very little benefit. So in this case I'm okay with not having a perfect solution, but one that is good enough.

**Comment by jshipley** [comment] 2024-08-06 17:33
I'm convinced. I hadn't considered the case of an extender being adjacent to multiple machines. That really does change everything, and letting the machine initialize the addon network does seem to be the best decision.

**Comment by Rearth** [comment] 2024-08-06 19:14
Great, I'll close this issue then

**Closed as completed by Rearth** 2024-08-06 19:14 UTC
